#!/bin/bash

if [ "$1" = 'exited' ]; then
    docker ps -a | grep 'Exited' | awk '{print $1}' | xargs docker rm

elif [ "$1" = 'pycharm' ]; then
    docker ps -a | grep 'pycharm' | awk '{print $1}' | xargs docker rm
    docker images | grep 'pycharm' | awk '{print $3}' | xargs docker rmi -f

elif [ "$1" = 'none' ]; then 
    docker images | grep '<none>' | awk '{print $3}' | xargs docker rmi

elif [ "$1" = 'webcelery' ]; then
    docker ps -a | grep 'web' | awk '{print $1}' | xargs docker rm -f
    docker ps -a | grep 'celery' | awk '{print $1}' | xargs docker rm -f

elif [ "$1" = 'all' ]; then
    docker ps -a | grep 'Exited' | awk '{print $1}' | xargs docker rm
    docker ps -a | grep 'pycharm' | awk '{print $1}' | xargs docker rm
    docker images | grep 'pycharm' | awk '{print $3}' | xargs docker rmi -f
    docker images | grep '<none>' | awk '{print $3}' | xargs docker rmi -f
    docker ps -a | grep 'web' | awk '{print $1}' | xargs docker rm -f
    docker ps -a | grep 'celery' | awk '{print $1}' | xargs docker rm -f
else
   echo
   echo "Usage: ./cleandocker exited | pycharm | none | webcelery | all"
   echo
fi

docker images
docker ps -a

