web:
  restart: always
  build: ./web/
  ports:
    - "80:80"
  expose:
    - "80"
  links:
    - postgres:postgres
    - rabbitmq:rabbitmq
  volumes_from:
    - code
    - static
    - media
    - logs
  command: run

postgres:
  restart: always
  build: ./postgres/
  volumes_from:
    - data
  expose:
    - "5432"

data:
  restart: always
  image: alpine
  volumes:
    - /var/lib/postgresql/data
  command: "true"

code:
  restart: always
  image: alpine
  volumes:
    - /app/lsg
  command: "true"

static:
  restart: always
  image: alpine
  volumes:
    - /app/static
  command: "true"

media:
  restart: always
  build: ./media/
  volumes:
    - /app/media
  command: "true"

logs:
  restart: always
  build: ./logs/
  volumes:
    - /app/logs
  command: "true"

rabbitmq:
  restart: always
  image: rabbitmq
  command: ""

celery:
  restart: always
  build: ./celery/
  links:
    - postgres:postgres
    - rabbitmq:rabbitmq
  volumes_from:
    - web
    - media
    - logs
  command: run

