# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20160815_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geocoder_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('United Kingdom', 'United Kingdom'), ('Ireland', 'Ireland'), ('Isle of Man', 'Isle of Man')], max_length=128),
        ),
    ]
