# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20161006_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
