# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:30
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='IE', max_length=2),
            preserve_default=False,
        ),
    ]
