# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0003_auto_20160810_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(choices=[(1, 'Easily'), (3, 'Hardly'), (2, 'Maybe')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamescollection',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gamescollection',
            name='user',
        ),
        migrations.DeleteModel(
            name='GamesCollection',
        ),
    ]
