# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160813_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
    ]
