# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160815_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='swaps_count',
        ),
        migrations.AddField(
            model_name='user',
            name='expired_swaps_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_swaps_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='neutral_feedback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='succeeded_swaps_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
