# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160826_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_url',
            field=models.URLField(blank=True, default='/static/img/user-icon.svg', null=True),
        ),
    ]
