# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160829_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
