# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_picture_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='user',
            name='social_picture_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/img/users/%Y/%m/%d/'),
        ),
    ]
