# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160904_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone2',
        ),
        migrations.AddField(
            model_name='user',
            name='phone1_prefix',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='world.Address'),
        ),
    ]
