# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
