# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20161125_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance_unit',
            field=models.CharField(choices=[('km', 'Km'), ('mi', 'Miles')], default='mi', max_length=10),
        ),
    ]
