# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20161211_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='platforms',
        ),
    ]
