# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_updates',
            field=models.BooleanField(default=False),
        ),
    ]
