# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_accepted_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
