# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 23:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20161218_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpUserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_user_agent', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
