# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_httpuseragent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='httpuseragent',
            unique_together=set([('user', 'http_user_agent')]),
        ),
    ]
