# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20161220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpuseragent',
            name='http_user_agent',
            field=models.CharField(max_length=1024),
        ),
    ]
