# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20161221_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collection_ids_account_deleted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist_ids_account_deleted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
