# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pg_fts.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('release', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('players', models.PositiveIntegerField(blank=True, null=True)),
                ('co_op', models.BooleanField(default=False)),
                ('youtube', models.CharField(blank=True, max_length=128, null=True)),
                ('esrb', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('api_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('similar_count', models.IntegerField(default=0)),
                ('fts', pg_fts.fields.TSVectorField(default='', dictionary='english', editable=False, fields=(('name', 'A'),), null=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('console', models.CharField(blank=True, max_length=128, null=True)),
                ('controller', models.CharField(blank=True, max_length=128, null=True)),
                ('developer', models.CharField(blank=True, max_length=128, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('memory', models.CharField(blank=True, max_length=255, null=True)),
                ('graphics', models.CharField(blank=True, max_length=255, null=True)),
                ('sound', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('media', models.CharField(blank=True, max_length=128, null=True)),
                ('max_controllers', models.PositiveIntegerField(blank=True, null=True)),
                ('api_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='games.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='similar',
            field=models.ManyToManyField(to='games.Game'),
        ),
        migrations.AlterIndexTogether(
            name='game',
            index_together=set([('name', 'platform')]),
        ),
    ]
