# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160829_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScripting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_last_updated', models.DateTimeField(blank=True, null=True)),
                ('games_images_last_updated', models.DateTimeField(blank=True, null=True)),
                ('games_thumbnails_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
