# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamescripting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameScripting',
        ),
    ]
