# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_delete_gamescripting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='fts',
        ),
    ]
