# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 11:46
from __future__ import unicode_literals

from django.db import migrations
import pg_fts.fields

from pg_fts.migrations import (CreateFTSIndexOperation, CreateFTSTriggerOperation,
                               UpdateVectorOperation)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='fts',
            field=pg_fts.fields.TSVectorField(default='', dictionary='english', editable=False, fields=(('name', 'A'),), null=True, serialize=False),
        ),
        UpdateVectorOperation('Game', 'fts'),
        CreateFTSTriggerOperation('Game', 'fts'),
        CreateFTSIndexOperation('Game', 'fts', index='gin')
    ]
