# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='similar_same_platform',
            field=models.ManyToManyField(related_name='similar_game_same_platform', to='games.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='similar_same_platform_ids',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='similar',
            field=models.ManyToManyField(related_name='same_game_other_platform', to='games.Game'),
        ),
    ]
