# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20161223_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='similar_same_platform_ids',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
