# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20161224_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='wanted_count',
            field=models.IntegerField(default=0),
        ),
    ]
