# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0018_auto_20160827_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('send_at', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('context_json', jsonfield.fields.JSONField(blank='', null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('swap_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.SwapRequest')),
            ],
        ),
    ]
