# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=128)),
                ('task_id', models.CharField(editable=False, max_length=128)),
                ('log', models.FilePathField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scripting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_last_updated', models.DateTimeField(blank=True, null=True)),
                ('games_images_last_updated', models.DateTimeField(blank=True, null=True)),
                ('games_thumbnails_last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='celerytask',
            name='scripting',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='scripts.Scripting'),
        ),
    ]
