# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='log',
            field=models.FilePathField(editable=False, max_length=512),
        ),
    ]
