# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_auto_20160831_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='task_id',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
