# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import request.flow


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.NullBooleanField()),
                ('review', models.CharField(blank=True, max_length=255, null=True)),
                ('offered_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Accepted'), (6, 'Cancelled'), (5, 'Failed'), (1, 'Pending'), (3, 'Refused'), (4, 'Succeeded')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('requested', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_of', to='request.Swap')),
                ('requester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='request.Swap')),
            ],
            bases=(models.Model, request.flow.StatusMethodsMixin),
        ),
    ]
