# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_swap_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='usage_condition',
            field=models.CharField(choices=[('bad', 'Bad'), ('good', 'Good'), ('very_good', 'Very Good')], default='good', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swap',
            name='usage_condition_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
