# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20160817_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='requested',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='requester',
        ),
    ]
