# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20160818_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap',
            name='offered_game',
        ),
        migrations.RemoveField(
            model_name='swap',
            name='user',
        ),
        migrations.DeleteModel(
            name='SwapRequest',
        ),
        migrations.DeleteModel(
            name='Swap',
        ),
    ]
