# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request.flow


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0005_auto_20160818_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_feedback', models.NullBooleanField()),
                ('requester_game_condition', models.CharField(choices=[('bad', 'Bad'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=16)),
                ('requested_feedback', models.NullBooleanField()),
                ('requested_game_condition', models.CharField(choices=[('bad', 'Bad'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=16)),
                ('requester_game_condition_notes', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(2, 'Accepted'), (6, 'Cancelled'), (5, 'Failed'), (1, 'Pending'), (3, 'Refused'), (4, 'Succeeded')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_requests', to='games.Game')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to=settings.AUTH_USER_MODEL)),
                ('requester_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_requests', to='games.Game')),
            ],
            bases=(models.Model, request.flow.StatusMethodsMixin),
        ),
    ]
