# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_game_condition_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
