# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20160818_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='requested_feedback',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='requester_feedback',
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requested_swapped',
            field=models.SmallIntegerField(choices=[(-1, 'Not Swapped'), (0, 'Not Yet'), (1, 'Swapped')], default=0),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester_swapped',
            field=models.SmallIntegerField(choices=[(-1, 'Not Swapped'), (0, 'Not Yet'), (1, 'Swapped')], default=0),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Accepted'), (8, 'Archived'), (2, 'Cancelled'), (5, 'Closing'), (7, 'Failed'), (1, 'Pending'), (4, 'Refused'), (6, 'Succeeded')], default=1),
        ),
    ]
