# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20160820_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_feedback',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Bad'), (1, 'Good'), (0, 'Neutral')], null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester_feedback',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Bad'), (1, 'Good'), (0, 'Neutral')], null=True),
        ),
    ]
