# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20160820_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='requested_game_condition',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='requester_game_condition',
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requested_swapped',
            field=models.SmallIntegerField(choices=[(-1, 'Not Swapped'), (1, 'Swapped'), (0, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requester_swapped',
            field=models.SmallIntegerField(choices=[(-1, 'Not Swapped'), (1, 'Swapped'), (0, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Accepted'), (8, 'Archived'), (2, 'Cancelled'), (7, 'Failed'), (5, 'Finalizing'), (1, 'Pending'), (4, 'Refused'), (6, 'Succeeded')], default=1),
        ),
    ]
