# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_auto_20160821_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='automatically_refused',
            field=models.NullBooleanField(),
        ),
    ]
