# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_swaprequest_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='status_history',
            field=jsonfield.fields.JSONField(blank='', null=True),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Archived'), (2, 'Cancelled'), (7, 'Failed'), (5, 'Finalizing'), (3, 'Ongoing'), (1, 'Pending'), (4, 'Refused'), (6, 'Succeeded'), (8, 'Timed Out')], default=1),
        ),
    ]
