# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_auto_20160823_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_feedback_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester_feedback_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requested_game_condition_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requester_game_condition_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(9, 'Archived'), (2, 'Cancelled'), (8, 'Expired'), (7, 'Failed'), (5, 'Finalizing'), (3, 'Ongoing'), (1, 'Pending'), (4, 'Refused'), (6, 'Succeeded')], default=1),
        ),
    ]
