# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0015_auto_20160825_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='requested_swapped',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='requester_swapped',
        ),
    ]
