# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0016_auto_20160826_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_swapped',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester_swapped',
            field=models.NullBooleanField(),
        ),
    ]
