# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0017_auto_20160826_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='requested_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='requester_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Cancelled'), (8, 'Expired'), (7, 'Failed'), (5, 'Finalizing'), (3, 'Ongoing'), (1, 'Pending'), (4, 'Refused'), (6, 'Succeeded')], default=1),
        ),
    ]
