# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0018_auto_20160827_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='distance',
        ),
    ]
